### ISSUE TITLE
Update Github's Issues for milestone v1.1

### ISSUE THREAD

**Issue by junrong09** [CS2103-AY1819S1-W10-4/main#16]
Please include the tasks to be completed for v1.1.
Each feature should be broken down into tasks completable within a day (or hours).

Feel free to plan and add in your forecasted tasks for future milestones.

**IMPORTANT**
Once done, please leave a "Done!" comment below. This applies to **all future milestone trackings**.
An issue will only be closed after all assignees have commented with the "Done!" comment.
All issues must be resolved for a milestone to be completed.

**Comment by junrong09** [comment]
Done!

**Comment by barkhyehyeon** [comment]
Done!

**Comment by AlecNgZW** [comment]
Done!

**Comment by junrong09** [comment]
Issues updated with tasks
