### ISSUE TITLE
User feedback from PE dry run

### ISSUE THREAD

**Issue by NancyQuris** [CS2103-AY1819S1-W10-4/main#185]
Hello W10-4, I tested your product during PE dry run but unfortunately I did not manage to post my feedback on the issue tracker, sorry :( As instructed by Prof Damith, I was suggested to post my user feedback here! I hope it will more or less help you! Below are my user experiences:
- I really appreciate your project for the richness of the content and functions. The exploration of the product is really interesting 👍 
- I wonder if there is any problem with the display of newly added recipe on the recipe panel. When I add a new recipe, it seems that the recipe is not being displayed.
<img width="1280" alt="screenshot 2018-11-03 at 12 03 17 pm" src="https://user-images.githubusercontent.com/32136736/47947905-bc12c000-df60-11e8-992b-fb3a5fd0eaa9.png">

- I wonder if my way to add recipe with `i/` prefix for instructions is correct, it seems that the instruction as mentioned in user guide does not work very well.
<img width="1280" alt="screenshot 2018-11-03 at 12 06 42 pm" src="https://user-images.githubusercontent.com/32136736/47947918-101da480-df61-11e8-9b7b-04aeea49f100.png">

- I think there is an inconsistency between the actually implementation and user guide. It seems that edit command for ingredient does not support "_" to link the name that user want to change.
<img width="1280" alt="screenshot 2018-11-03 at 12 24 01 pm" src="https://user-images.githubusercontent.com/32136736/47948028-70ade100-df63-11e8-8b23-6634251c3e57.png">

- I am not sure if plan command works as expected. I found out that when I entered plan command, it throw failure messages.
<img width="1280" alt="screenshot 2018-11-03 at 12 20 13 pm" src="https://user-images.githubusercontent.com/32136736/47948006-d9e12480-df62-11e8-8e74-b8e1f7347343.png">

All in all, except for the small exceptions, the product works quite fine and the functions that it supports are really useful! Thank you for your effort!!

**Comment by junrong09** [comment]
@NancyQuris Thanks so much for ur in-depth review. Appreciate that. I think we have more to work on.

**Comment by NancyQuris** [comment]
Thank you for replying! Wish you test all the best! Jiayou!!

**Comment by barkhyehyeon** [comment]
Fixed the issue regarding edit command for ingredient.

**Comment by BennTay** [comment]
Updated the plan meal command usage instructions to specify that dates have to range from the present to the future. Thanks for the feedback!
